config/routes.rb
Rails.application.routes.draw do
  resources :keys
  devise_for :users, skip: [:registrations]

  root 'keys#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/key.rb
class Key < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
  before_action :set_key, only: [:show, :edit, :update, :destroy]

  # GET /keys
  # GET /keys.json
  def index
    @keys = Key.all
  end

  # GET /keys/1
  # GET /keys/1.json
  def show
  end

  # GET /keys/new
  def new
    @key = Key.new
  end

  # GET /keys/1/edit
  def edit
  end

  # POST /keys
  # POST /keys.json
  def create
    @key = Key.new(key_params)
    @key.user = current_user
    respond_to do |format|
      if @key.save
        format.html { redirect_to @key, notice: 'Key was successfully created.' }
        format.json { render :show, status: :created, location: @key }
      else
        format.html { render :new }
        format.json { render json: @key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keys/1
  # PATCH/PUT /keys/1.json
  def update
    respond_to do |format|
      if @key.update(key_params)
        format.html { redirect_to @key, notice: 'Key was successfully updated.' }
        format.json { render :show, status: :ok, location: @key }
      else
        format.html { render :edit }
        format.json { render json: @key.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keys/1
  # DELETE /keys/1.json
  def destroy
    @key.destroy
    respond_to do |format|
      format.html { redirect_to keys_url, notice: 'Key was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_key
      @key = Key.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def key_params
      params.require(:key).permit(:user_id, :password, :local)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keys_helper.rb
module KeysHelper
end

app/views/keys/_form.html.erb
<%= form_with(model: key, local: true) do |form| %>
  <% if key.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(key.errors.count, "error") %> prohibited this key from being saved:</h2>

      <ul>
        <% key.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :local %>
    <%= form.text_field :local %>
  </div>
  
  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/keys/edit.html.erb
<h1>Editing Key</h1>

<%= render 'form', key: @key %>

<%= link_to 'Show', @key %> |
<%= link_to 'Back', keys_path %>

app/views/keys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Keys</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Password</th>
      <th>Local</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keys.each do |key| %>
      <tr>
        <td><%= key.user_id %></td>
        <td><%= key.password %></td>
        <td><%= key.local %></td>
        <td><%= link_to 'Show', key %></td>
        <td><%= link_to 'Edit', edit_key_path(key) %></td>
        <td><%= link_to 'Destroy', key, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Key', new_key_path %>

app/views/keys/new.html.erb
<h1>New Key</h1>

<%= render 'form', key: @key %>

<%= link_to 'Back', keys_path %>

app/views/keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @key.user_id %>
</p>

<p>
  <strong>Password:</strong>
  <%= @key.password %>
</p>

<p>
  <strong>Local:</strong>
  <%= @key.local %>
</p>

<%= link_to 'Edit', edit_key_path(@key) %> |
<%= link_to 'Back', keys_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magickey</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <br>
    <%= link_to 'Sair', destroy_user_session_path , method: :delete %>
  </body>
</html>